# Site settings
title: B.R.I.D.G.E.S.
description: "Bridging Real-world Infastructure Designed to Goal-align, Engage, and Stimulate."
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
